name = "shared-tab-sync"
compatibility_date = "2025-01-01"
main = "workers/app.ts"

[assets]
directory = "./dist/client"

[alias]
"virtual:react-router/server-build" = "./dist/server/index.js"

[[d1_databases]]
binding = "shared_tab_sync_db"
database_name = "shared-tab-sync-db"
database_id = "be9181c1-912a-46c7-8fbc-39cb21aef3bb"

[[durable_objects.bindings]]
name = "ROOM"
class_name = "RoomObject"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RoomObject"]
